SERVER_IP   = "192.168.56.110"
SERVER_HOST = "rsterinS"

Vagrant.configure("2") do |config|
    config.vm.box = "debian/trixie64"
    config.vm.box_check_update = false
    config.vm.boot_timeout = 600

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider "libvirt" do |lv|
        lv.driver         = "kvm"
        lv.cpu_mode       = "host-passthrough"
        lv.cpus           = 1
        lv.memory         = 1024
        lv.default_prefix = ""
    end

    # Server (K3s controller) hosting the three applications
    config.vm.define SERVER_HOST do |server|
        server.vm.hostname = SERVER_HOST
        server.vm.network "private_network", ip: SERVER_IP
        server.vm.provision "file", source: "conf", destination: "/tmp/conf"
        server.vm.provision "shell", path: "scripts/server.sh", args: [SERVER_IP]
    end
end
