CONTROL_IP   = "192.168.56.110"
WORKER_IP    = "192.168.56.111"
CONTROL_HOST = "rsterinS"
WORKER_HOST  = "rsterinSW"
K3S_TOKEN    = "IvZm4q4OEhd78ObdZS8LJEfqsemGu77KASPg6tWU9E4iab9CCOVuKuZ2ya8PthyA"

Vagrant.configure("2") do |config|
    config.vm.box = "debian/trixie64"
    config.vm.box_check_update = false
    config.vm.boot_timeout = 600

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider "libvirt" do |lv|
        lv.driver         = "kvm"
        lv.cpu_mode       = "host-passthrough"
        lv.cpus           = 1
        lv.memory         = 1024
        lv.default_prefix = ""
    end

    # Server (K3s controller)
    config.vm.define CONTROL_HOST do |control|
        control.vm.hostname = CONTROL_HOST
        control.vm.network "private_network", ip: CONTROL_IP
        control.vm.provision "shell", path: "scripts/server.sh", args: [CONTROL_IP, K3S_TOKEN]
    end

    # ServerWorker (K3s agent)
    config.vm.define WORKER_HOST do |worker|
        worker.vm.hostname = WORKER_HOST
        worker.vm.network "private_network", ip: WORKER_IP
        worker.vm.provision "shell", path: "scripts/worker.sh", args: [CONTROL_IP, WORKER_IP, K3S_TOKEN]
    end
end
